server.port: 8888

eureka:
  client:
    serviceUrl.defaultZone: 'http://localhost:8761/eureka/'
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true

spring:
  application.name: 'config-service'
  cloud:
    config.server.git:
      uri: 'https://github.com/Online-shop-app/cloud-configs.git'
      clone-on-start: true
      username: '${ONLINE_SHOP_CONFIG_REPO_USERNAME}'
      password: '${ONLINE_SHOP_CONFIG_REPO_TOKEN}'
